#Title link
title: "Luggage"

#Username and bcrypt password hash
username: 'USERNAME'
password_hash: 'PASSWORD_HASH'

#absolute file path for uploading files, needs to be writable by your
#unicorns
upload_path: 'UPLOAD_PATH'


#This is the url you go to in order to visit luggage such as:
#http://goodorobot.net/luggage
base_url: "BASE_URL"

#This is the url you would like to use to serve static files, such as
#the files that have been uploaded and the javascript and css for
#luggage. This url should mapped to a folder that contains /uploads and
#/assests for luggage
static_url: 'STATIC_URL'


#Database info
db_adapter: 'sqlite3'
db_name: 'luggage.db'

#If adatper is mysql or postrgesql use these:
#db_host: 'localhost'
#db_username: 'luggage_user'
#db_password: 'anybodywantapeanut?'

#How many items to display on the index
items_per_page: 15
